In [1]:
import numpy as np

In [19]:
#1.
a1 = np.random.rand(15)*2
a1

array([0.01743784, 0.45062394, 1.42588157, 1.96961604, 0.34890067,
       1.98323669, 1.7358274 , 0.60676321, 1.91505928, 1.6728754 ,
       0.23428694, 0.61696613, 0.20950329, 0.00435748, 0.42681407])

In [23]:
#2.
a2 = np.random.rand(36).reshape(6,6)*5
a2

array([[0.46376586, 3.19642838, 3.26282408, 2.57348956, 0.93559699,
        0.63439603],
       [2.29853856, 1.13401858, 4.38056109, 1.28840145, 1.30921076,
        2.46049402],
       [3.44737184, 3.67104483, 0.58494218, 2.8921392 , 1.96046005,
        4.31000249],
       [3.61108289, 4.91675607, 2.54531902, 0.69059793, 3.07526082,
        0.55545693],
       [2.84133852, 0.02941393, 2.68590515, 3.64908388, 3.14601528,
        4.77973967],
       [4.9324762 , 2.66394943, 4.65666103, 0.92512317, 3.49679983,
        2.72013957]])

In [28]:
#3.
a3 = np.random.rand(27).reshape(3,3,3)
all_mean = a3.mean()
column_mean =a3.mean(axis = 0) 
axis2_mean =a3.mean(axis = 2) 
print(all_mean)
print(column_mean)
print(axis2_mean)

0.47806244753664223
[[0.46249101 0.47282041 0.64022769]
 [0.50611675 0.10724927 0.35942638]
 [0.84760564 0.57918147 0.3274434 ]]
[[0.85667604 0.50011091 0.53321079]
 [0.33221846 0.30858142 0.61532631]
 [0.38664461 0.16410008 0.6056934 ]]


In [30]:
#4.1 sort
a41 = np.random.rand(15)*2
print(np.sort(a41))

#4.2 

[0.16742153 0.27501698 0.43717672 0.55418367 0.59068483 0.60882641
 0.7980856  0.97236073 1.12349003 1.40124887 1.46666068 1.4897453
 1.67001136 1.70406245 1.76013559]


In [33]:
#4.2 外積
a42 = np.random.rand(15)*2
b42 = np.random.rand(15)*2

result= np.outer(a42, b42)

print(result)

[[1.29637631 3.53464928 1.32787621 1.16244236 2.8148423  2.4348168
  3.11568505 3.55411478 0.15630184 2.44046792 2.25331641 2.40439357
  3.00954067 0.56640184 1.21000583]
 [1.02407476 2.79220243 1.04895815 0.9182734  2.22358964 1.92338783
  2.4612409  2.80757924 0.12347092 1.92785194 1.78001127 1.89935495
  2.37739196 0.44743014 0.95584624]
 [0.42277036 1.15270925 0.43304302 0.37909223 0.91796795 0.79403517
  1.01607788 1.15905728 0.05097269 0.7958781  0.7348448  0.78411364
  0.9814624  0.18471327 0.39460348]
 [0.59177577 1.61351282 0.60615498 0.53063699 1.28493205 1.11145627
  1.42226211 1.62239852 0.07134938 1.11403592 1.02860415 1.09756854
  1.37380884 0.2585537  0.55234898]
 [0.53171298 1.44974796 0.54463277 0.47677954 1.15451677 0.99864807
  1.27790841 1.4577318  0.06410771 1.0009659  0.92420509 0.98616989
  1.23437294 0.23231157 0.49628785]
 [1.26370885 3.44557944 1.29441498 1.13314991 2.74391092 2.37346171
  3.03717272 3.46455444 0.15236318 2.37897043 2.19653496 2.34380512
  2.9